site_name: ph的题解区
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  
extra_javascript:
  - javascripts/katex.js 
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css

nav:
- codeforces:
  - cf1: 
    - a: codeforces/1/a.md
    - b: codeforces/1/b.md
    - c: codeforces/1/c.md
  - cf2:
    - a: codeforces/2/a.md
    - b: codeforces/2/b.md
    - c: codeforces/2/c.md
  - cf3:
    - a: codeforces/3/a.md
    - b: codeforces/3/b.md
    - c: codeforces/3/c.md
    - d: codeforces/3/d.md
  - cf4:
    - a: codeforces/4/a.md
    - b: codeforces/4/b.md
    - c: codeforces/4/c.md
    - d: codeforces/4/d.md
- atcoder:
  - abc462:
    - a: atcoder/abc462/a.md
    - b: atcoder/abc462/b.md
    - c: atcoder/abc462/c.md
    - d: atcoder/abc462/d.md
    - e: atcoder/abc462/e.md
    - f: atcoder/abc462/f.md
  - abc463:
    - a: atcoder/abc463/a.md
    - b: atcoder/abc463/b.md
    - c: atcoder/abc463/c.md
    - d: atcoder/abc463/d.md
    - e: atcoder/abc463/e.md
  - arc222:
    - a: atcoder/arc222/a.md
